# Generated by Django 5.1.6 on 2025-02-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0004_alter_servidor_options_alter_servidor_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='servidor',
            managers=[
            ],
        ),
    ]
