# Generated by Django 5.1.6 on 2025-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_alter_servidor_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
