# Generated by Django 5.1.6 on 2025-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0006_servidor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='is_active',
        ),
    ]
