# Generated by Django 5.1.6 on 2025-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0007_remove_servidor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=10),
        ),
    ]
