# Generated by Django 5.1.6 on 2025-02-27 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0008_alter_servidor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente_tipo', models.CharField(choices=[('sala', 'Sala'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório')], max_length=20)),
                ('ambiente_numero', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('aprovada', 'Aprovada'), ('pendente', 'Pendente'), ('reprovada', 'Reprovada')], default='pendente', max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
