# Generated by Django 5.1.6 on 2025-03-02 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0009_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
