# Generated by Django 5.1.6 on 2025-03-02 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0010_alter_reserva_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
